name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: booking_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1111
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Use BOT_NAME secret
        env:
          BOT_NAME: ${{ secrets.BOT_NAME }}
        run: echo "Using BOT_NAME secret"
      - name: Use BOT_TOKEN secret
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: echo "Using BOT_TOKEN secret"
      - name: Wait for PostgreSQL
        id: wait-for-postgres
        run: echo "Waiting for PostgreSQL to be ready..." && sleep 20
      - name: Check PostgreSQL readiness
        run: |
          until docker exec postgres pg_isready --dbname=booking_db; do
            echo "PostgreSQL is not ready yet - sleeping"
            sleep 5
          done
        if: steps.wait-for-postgres.outputs.result == 'success'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
