name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: booking_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1111
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Wait for PostgreSQL
        run: docker exec postgres pg_isready --dbname=booking_db
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
